### ISSUE TITLE
Godocs

### ISSUE THREAD

**Issue by danthegoodman1** [cockroachdb/cockroachdb-parser#5]
Would be sublime if godocs were generated and linked :D

**Comment by otan** [comment]
any instructions i can follow to get that setup? :)

**Comment by danthegoodman1** [comment]
@otan See https://pkg.go.dev/about#:~:text=packages%20and%20modules.-,Adding%20a%20package,-Data%20for%20the

**Comment by danthegoodman1** [comment]
https://go.dev/blog/godoc for generation but I assume they are already there for the most part if they are pulled from the main repo

**Comment by danthegoodman1** [comment]
https://pkg.go.dev/github.com/cockroachdb/cockroachdb-parser is bland at the top level, but I can navigate down into the sub packages already

**Comment by danthegoodman1** [comment]
https://pkg.go.dev/github.com/cockroachdb/cockroachdb-parser@v0.0.0-20221108120757-a1ab1810b088/pkg/sql/parser#section-readme is a bit messy but more what we are looking for :D

**Comment by otan** [comment]
i think i added it, sorry for the slow follow up
